version: '3'

services:
  jenkins:
    build:
      context: .
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ../.:/mnt/cicd-django-demo:ro
    command: /mnt/cicd-django-demo/jenkins-local/start-jenkins.sh
