version: '3'

services:
  jenkins:
    build:
      context: .
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - ../.:/mnt/cicd-django-demo:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    # INSECURE SETTING
    command: /mnt/cicd-django-demo/jenkins-local/start-jenkins.sh