name: Build-Test-Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 14 * * *'  # This schedule runs every day at 9 AM Chicago time (14:00 UTC)


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:

  build-test-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show runs-on Details
      run: |
        set -x
        lscpu
        free -h
        df -h
        docker version
        python --version
        whoami
  
    - name: Build the Builder Docker image (Unit Tests, Security Checks, Compliance, Wheels)
      run: docker buildx build --target builder -t  simple-task-app-builder:latest .

    - name: Build the Application Docker image
      run: docker buildx build --target application --tag ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app:latest .

    - name: Docker images
      run: docker image ls -a

    # - name: Selenium
    #   run: |
    #     pip install selenium docker
    #     cd app/
    #     TAG=latest python -m unittest test_selenium.py --verbose

    # - name: ClamAV Scan Application Image
    #   run: docker build --build-arg base_image=simple-task-app:latest -f Dockerfile-clamav.dockerfile -t simple-task-app-testing-temp-clamav  .
    
    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v4
    #   with:
    #     images: nickstanley574/simple-task-app
    
    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # - name: Push Docker Images
    #   run: |
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app:latest

    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}