name: Build-Test-Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 14 * * *'  # This schedule runs every day at 9 AM Chicago time (14:00 UTC)


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:

  build-test-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show runs-on Details
      run: |
        set -x
        lscpu
        free -h
        df -h
        docker version
        python --version
        whoami

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  
    - name: Build the Builder Docker image (Unit Tests, Security Checks, Compliance, Wheels)
      run: docker buildx build --target builder -t simple-task-app-builder:latest .

    - name: Build the Application Docker image
      run: |
        docker buildx build \
        --target application \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app:${{ steps.vars.outputs.sha_short }} \
        .

    - name: Docker images
      run: docker image ls -a

    # - name: Selenium
    #   run: |
    #     pip install selenium docker
    #     cd app/
    #     TAG=latest python -m unittest test_selenium.py --verbose

    # - name: ClamAV Scan Application Image
    #   run: docker build --build-arg base_image=simple-task-app:latest -f Dockerfile-clamav.dockerfile -t simple-task-app-testing-temp-clamav  .
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Images
      run: |
        git_short_sha=$(git rev-parse --short HEAD)
        
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-task-app:${{ steps.vars.outputs.sha_short }
