name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show runs-on Details
      run: |
        lscpu
        free -h
        df -h
        whoami
    - name: Build the Builder Docker image (Unit Tests, Security Checks, Compliance, Wheels)
      run: docker build --target builder -t  simple-task-app-builder:latest .
    - name: Build the Application Docker image
      run: docker build --target application --file Dockerfile --tag simple-task-app:latest .
    - name: Selenium
      run: |
        python --version
        pip install selenium docker
        cd app/
        TAG=latest python -m unittest test_selenium.py --verbose
    - name: ClamAV Scan
      run: docker build --build-arg base_image=simple-task-app:latest -f Dockerfile-clamav.dockerfile -t simple-task-app-testing-temp-clamav  .