name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Builder Docker image
      run: docker build --no-cache --target builder -t  my-image-name-builder:latest .
    - name: Build the Application Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: ClamAV Scan
      run: docker build --build-arg base_image=my-image-name:latest -f Dockerfile-clamav.dockerfile -t my-image-name-testing-temp-clamav  .
    - name: Selenium
      run: "python --version"